// Generated by scripts/write-release-identity.mjs before production builds.
// The committed fallback never pretends to be a deployed artifact.
export const GENERATED_RELEASE_COMMIT_SHA: string | undefined = undefined
export const GENERATED_PRODUCT_VERSION = '1.1.0-rc.1' as const
export const GENERATED_RELEASE_CHANNEL = 'prerelease' as const
export const GENERATED_MCP_CONTRACT_HASH = 'unbound' as const
export const GENERATED_MIGRATION_SET = [] as const
export const GENERATED_MIGRATION_SET_HASH = 'unbound' as const
export const GENERATED_SNAPSHOT_SCHEMA = 'pjsdas-local-snapshot' as const
export const GENERATED_SNAPSHOT_VERSION = 1 as const
