// Generated by scripts/write-release-identity.mjs before production builds.
// The committed fallback stays undefined so source checkouts never pretend to
// represent a deployment until a build has bound them to a concrete commit.
export const GENERATED_RELEASE_COMMIT_SHA: string | undefined = undefined
