import {describe,expect,it,vi}from'vitest'
import{createAuthoritativeCommandExecutor}from'../gateway/authoritativeCommands.js'
import{createTransactionalWorkspaceStore}from'../gateway/transactionalWorkspaceStore.js'
import{createPrivateReminderManagementTools}from'../gateway/privateReminderManagementTools.js'
import{assertPrivateReminderManagementGrant,type PrivateReminderManagementGrant}from'../gateway/privateReminderManagementAccess.js'
import{privateReminderManagementFingerprint as fp}from'../src/privateReminderManagement.js'
import{unknownDeadlineWorkspace}from'./fixtures/unknownDeadlineWorkspace.js'
const owner='00000000-0000-4000-8000-000000000001',client='00000000-0000-4000-8000-000000000002',id='00000000-0000-4000-8000-000000000003'
const principal={kind:'delegated_mcp'as const,userId:owner,clientId:client}
const grant:PrivateReminderManagementGrant={id,revision:1,userId:owner,clientId:client,consentVersion:6,capability:'workspace.reminders.manage',grantedAt:'2026-10-01T00:00:00Z'}
function fixture(){const s=unknownDeadlineWorkspace(1);s.data.scheduleNodes!.push({id:'private-target',occurrenceId:'private-occurrence',version:1,kind:'interview',state:'scheduled',temporal:{shape:'fixed_range',precision:'datetime',timezone:'UTC',startAt:'2026-10-03T02:00:00Z',endAt:'2026-10-03T03:00:00Z',resolutionBasis:'user_explicit'},constraintKind:'user_plan',evidenceRefs:[],sourceVersionRefs:[],relatedActionIds:[],relatedPrepIds:[],createdAt:'2026-10-02T00:00:00Z',updatedAt:'2026-10-02T00:00:00Z'});return s}
async function command(s=fixture()){return{commandId:'private-reminder-command',baseRevision:0,command:{type:'private_reminder_management',value:{operations:[{kind:'create_private_reminder',scheduleNodeId:'private-target',expectedNodeFingerprint:await fp(s.data.scheduleNodes!.at(-1)),purpose:'custom',triggerAt:'2026-10-03T01:00:00Z'}]}}}}
function storeFixture(){let snapshot=fixture(),revision=0;const records:any[]=[],posts:any[]=[];const fetchImpl=vi.fn<typeof fetch>(async(input,init)=>{
 const u=new URL(String(input));if(init?.method==='POST'){const b=JSON.parse(String(init.body));posts.push({path:u.pathname,body:b});snapshot=b.target_snapshot;revision++;const receipt=b.target_receipt_context;records.push({command_id:b.target_command_id,operation:b.target_operation,payload_hash:b.target_payload_hash,resulting_revision:revision,receipt,compensation:b.target_compensation});return Response.json([{outcome:'COMMITTED',workspace_id:'fixture',revision,receipt}])}
 expect(u.searchParams.get('user_id')).toBe(`eq.${owner}`)
 if(u.pathname.endsWith('pjsdas_workspaces'))return Response.json([{id:'fixture',user_id:owner,revision,snapshot,schema_version:4}])
 const selector=u.searchParams.get('command_id'),after=u.searchParams.get('resulting_revision');return Response.json(records.filter(r=>(!selector||selector===`eq.${r.command_id}`)&&(!after||r.resulting_revision>Number(after.slice(3)))))
 });return{records,posts,fetchImpl,snapshot:()=>snapshot,options:{supabaseUrl:'https://fixture.invalid',serviceRoleKey:'fixture-only',fetchImpl}}}
describe('v6 private reminder admission and atomic store',()=>{
 it.each([undefined,...[1,2,3,4,5].map(consentVersion=>({...grant,consentVersion})),{...grant,capability:'workspace.manage'},{...grant,userId:client},{...grant,clientId:owner},{...grant,revokedAt:'2026-10-02T00:00:00Z'},{...grant,revision:0},{...grant,grantedAt:'2999-01-01T00:00:00Z'}])('rejects absent, older, foreign or stale proof %#',candidate=>{expect(()=>assertPrivateReminderManagementGrant(principal,candidate as any)).toThrow(/version-6/)})
 it('default denies before reading and never treats first-party session as delegated consent',async()=>{const f=storeFixture();const e=createAuthoritativeCommandExecutor(f.options);await expect(e.execute(principal,await command())).rejects.toThrow(/version-6/);expect(f.fetchImpl).not.toHaveBeenCalled();expect(()=>assertPrivateReminderManagementGrant({...principal,kind:'first_party_web'},grant)).toThrow()})
 it('commits/replays and awaits exact asynchronous restore through only the v6 RPC',async()=>{
  const f=storeFixture(),e=createAuthoritativeCommandExecutor({...f.options,resolvePrivateReminderManagementGrant:async()=>grant}),c=await command(),before=structuredClone(f.snapshot())
  const applied=await e.execute(principal,c);expect(applied.outcome).toBe('COMMITTED');expect((await e.execute(principal,c)).outcome).toBe('ALREADY_APPLIED');expect(f.posts).toHaveLength(1)
  expect(f.posts[0]).toMatchObject({path:'/rest/v1/rpc/pjsdas_commit_private_reminder_workspace_v1',body:{target_user_id:owner,target_client_id:client,target_grant_id:id,target_grant_revision:1}})
  const undo={commandId:'private-reminder-undo',targetCommandId:c.commandId,expectedCompensationFingerprint:applied.result!.compensationFingerprint}
  await expect(e.undo(principal,{...undo,expectedCompensationFingerprint:'f'.repeat(64)})).rejects.toThrow(/fingerprint/)
  expect((await e.undo(principal,undo)).outcome).toBe('COMMITTED');expect((await e.undo(principal,undo)).outcome).toBe('ALREADY_APPLIED');expect(f.posts).toHaveLength(2)
  expect(f.snapshot().data.reminderIntents).toEqual(before.data.reminderIntents);expect(f.snapshot().data.opportunities).toEqual(before.data.opportunities);expect(f.snapshot().data.scheduleNodes).toEqual(before.data.scheduleNodes)
  await expect(e.execute(principal,{...c,command:{...c.command,value:{operations:[{...c.command.value.operations[0],purpose:'prep'}]}}})).rejects.toThrow(/reused/)
 })
 it.each(['revoke','revision','replacement']as const)('binds proof across %s before precommit',async change=>{const f=storeFixture();let n=0;const e=createAuthoritativeCommandExecutor({...f.options,resolvePrivateReminderManagementGrant:async()=>++n===1?grant:change==='revoke'?undefined:{...grant,...(change==='revision'?{revision:2}:{id:'00000000-0000-4000-8000-000000000004'})}});await expect(e.execute(principal,await command())).rejects.toThrow(/authorization|changed/);expect(f.posts).toEqual([])})
 it('does not revive an old request on a replacement proof after CAS conflict',async()=>{const f=storeFixture();let current={...grant},calls=0;const fetchImpl:typeof fetch=async(input,init)=>{if(init?.method==='POST'){calls++;current.revision=2;return Response.json([{outcome:'CONFLICT',workspace_id:'fixture',revision:0,snapshot:f.snapshot(),receipt:{}}])}return f.fetchImpl(input,init)};const e=createAuthoritativeCommandExecutor({...f.options,fetchImpl,resolvePrivateReminderManagementGrant:async()=>current});await expect(e.execute(principal,await command())).rejects.toThrow(/changed/);expect(calls).toBe(1)})
 it('fails closed on wrong proof version and SQL denial without generic RPC fallback',async()=>{const fetchImpl=vi.fn<typeof fetch>(async()=>Response.json({code:'42501'},{status:403}));const store=createTransactionalWorkspaceStore({supabaseUrl:'https://fixture.invalid',serviceRoleKey:'fixture-only',fetchImpl});const c={userId:owner,clientId:client,principalKind:'delegated_mcp'as const,commandId:'reminder-deny',operation:'private_reminder_management',payloadHash:'hash',expectedRevision:0,snapshot:fixture(),schemaVersion:4,receiptContext:{},managementAuthorization:{grantId:id,grantRevision:1,consentVersion:5 as const}};await expect(store.commitAuthoritativeForUser(c)).rejects.toThrow(/version/);expect(fetchImpl).not.toHaveBeenCalled();await expect(store.commitAuthoritativeForUser({...c,managementAuthorization:{...c.managementAuthorization,consentVersion:6}})).rejects.toThrow(/before commit/);expect(fetchImpl).toHaveBeenCalledTimes(1)})
 it('withholds adapter read/noncommit data on revocation and internally binds execute admission',async()=>{
  const f=storeFixture();let calls=0;const adapter=createPrivateReminderManagementTools({principal,storeOptions:f.options,resolveGrant:async()=>++calls===1?grant:undefined})
  const result=await adapter.invoke('get_private_reminder_management',{type:'schedule_targets',ids:['private-target']});expect(result.structuredContent).toMatchObject({code:'AUTH_FORBIDDEN'});expect(JSON.stringify(result)).not.toContain('private-occurrence')
  calls=0;f.fetchImpl.mockClear();const c=await command();const denied=await adapter.invoke('execute_private_reminder_management',{commandId:c.commandId,baseRevision:0,change:c.command.value});expect(denied.structuredContent).toMatchObject({code:'AUTH_FORBIDDEN'});expect(f.fetchImpl).not.toHaveBeenCalled()
 })
 it('adapter execute/read/restore never returns full workspace or client compensation input',async()=>{const f=storeFixture(),adapter=createPrivateReminderManagementTools({principal,storeOptions:f.options,resolveGrant:async()=>grant}),c=await command();const applied=await adapter.invoke('execute_private_reminder_management',{commandId:c.commandId,baseRevision:0,change:c.command.value});expect(applied.structuredContent).toMatchObject({outcome:'COMMITTED'});expect(JSON.stringify(applied)).not.toContain('Synthetic Company');expect(JSON.stringify(applied)).not.toContain('private_reminder_management_restore');const got=await adapter.invoke('get_private_reminder_management',{type:'reminders'});expect((got.structuredContent as any).data.items).toHaveLength(1);const undo={commandId:'adapter-reminder-undo',targetCommandId:c.commandId,expectedCompensationFingerprint:(applied.structuredContent as any).result.compensationFingerprint};expect((await adapter.invoke('restore_private_reminder_management',{...undo,compensation:{payload:'injected'}})).isError).toBe(true);expect((await adapter.invoke('restore_private_reminder_management',undo)).structuredContent).toMatchObject({outcome:'COMMITTED'})})
})
