import { describe, expect, it, vi } from 'vitest'
import { buildScopedConsentDecision, createScopedConsentClient, scopedConsentViewSchema } from '../src/aiAccess/scopedManagementConsentClient.js'
import { SCOPED_MANAGEMENT_CONSENTS, scopedManagementConsentHash, scopedManagementDomains } from '../gateway/scopedManagementConsent.js'
const owner='00000000-0000-4000-8000-000000000001',client='00000000-0000-4000-8000-000000000002',requestId='00000000-0000-4000-8000-000000000003'
async function view(){return scopedConsentViewSchema.parse({account:{id:owner},descriptors:await Promise.all(scopedManagementDomains.map(async domain=>({domain,canApprove:true,consent:SCOPED_MANAGEMENT_CONSENTS[domain],consentTextHash:await scopedManagementConsentHash(domain)}))),clients:[{id:client,name:'Synthetic client',canApprove:true,grants:[]}]})}
describe('scoped client exact choices',()=>{
 it('never defaults an empty selection to any authority',async()=>{const v=await view();expect(()=>buildScopedConsentDecision(v,client,{},true,requestId)).toThrow();expect(()=>buildScopedConsentDecision(v,client,{planning:'approve'},false,requestId)).toThrow()})
 it('constructs only selected domains with the exact displayed account/version/hash and absent proof',async()=>{const v=await view(),b=buildScopedConsentDecision(v,client,{planning:'approve',privateReminder:'approve'},true,requestId);expect(b.choices.map(c=>c.domain)).toEqual(['planning','privateReminder']);expect(b.expectedAccountId).toBe(owner);expect(b.choices.every(c=>c.expectedGrant===null)).toBe(true)})
 it('refuses disconnected approval or revocation without an owned active proof',async()=>{const v=await view();v.clients[0].canApprove=false;expect(()=>buildScopedConsentDecision(v,client,{planning:'approve'},true,requestId)).toThrow();expect(()=>buildScopedConsentDecision(v,client,{planning:'revoke'},true,requestId)).toThrow()})
 it('rejects account switch during a read and before POST',async()=>{const v=await view();let calls=0;const request=vi.fn(async()=>Response.json(v));const c=createScopedConsentClient({getSession:async()=>({accountId:++calls===1?owner:client,accessToken:'synthetic'}),request});await expect(c.read()).rejects.toThrow(/账号/);const b=buildScopedConsentDecision(v,client,{planning:'approve'},true,requestId);await expect(c.decide(b)).rejects.toThrow(/账号/);expect(request).toHaveBeenCalledTimes(1)})
 it('treats partial/misbound receipts as uncertain instead of success',async()=>{const v=await view(),b=buildScopedConsentDecision(v,client,{planning:'approve'},true,requestId);const c=createScopedConsentClient({getSession:async()=>({accountId:owner,accessToken:'synthetic'}),request:async()=>Response.json({requestId,refreshRequired:true,receipts:[]})});await expect(c.decide(b)).rejects.toMatchObject({uncertain:true})})
 it('preserves uncertain pending intent on401 and exposes sign-in recovery',async()=>{const v=await view(),b=buildScopedConsentDecision(v,client,{planning:'approve'},true,requestId);const c=createScopedConsentClient({getSession:async()=>({accountId:owner,accessToken:'synthetic'}),request:async()=>Response.json({code:'AUTH_REQUIRED'},{status:401})});await expect(c.read()).rejects.toMatchObject({code:'SIGN_IN_REQUIRED'});await expect(c.decide(b)).rejects.toMatchObject({code:'SIGN_IN_REQUIRED',uncertain:true})})
 it('accepts only a structurally exact terminal denial as certain',async()=>{const v=await view(),b=buildScopedConsentDecision(v,client,{planning:'approve'},true,requestId);const c=createScopedConsentClient({getSession:async()=>({accountId:owner,accessToken:'synthetic'}),request:async()=>Response.json({requestId,refreshRequired:true,receipts:[{domain:'planning',outcome:'DENIED',grant_id:null,grant_revision:null}]})});await expect(c.decide(b)).rejects.toMatchObject({code:'CONSENT_DENIED',uncertain:false})})

})
