import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const workflow = readFileSync(new URL('../.github/workflows/deploy-pages.yml', import.meta.url), 'utf8')
const health = readFileSync(new URL('../api/health.ts', import.meta.url), 'utf8')

describe('backend-first release gate', () => {
  it('refuses to publish until the exact backend build and required MCP tool surface are advertised', () => {
    expect(workflow).toContain('Wait for exact matching production backend')
    expect(workflow).toContain('PJSDAS_BACKEND_ORIGINS')
    expect(workflow).toContain('${origin}/api/health')
    expect(workflow).toContain('health.version === "1.10.0-alpha.1"')
    expect(workflow).toContain('const expectedMode = expectedAuthority === "transactional" ? "transactional-connected" : "google-drive-trusted-ingestion"')
    expect(workflow).toContain('health.mode === expectedMode')
    expect(workflow).toContain('health.workspaceAuthority === expectedAuthority')
    expect(workflow).toContain('health.release?.commitSha === process.env.GITHUB_SHA')
    expect(workflow).toContain('capabilities.authenticatedMcpToolSurface === true')
    expect(workflow).toContain('capabilities.delegatedCredentialIsolation === true')
    expect(workflow).toContain('capabilities.trustedIngestionGrantModel === "v1"')
    expect(workflow).toContain('capabilities.transactionalWorkspaceFoundation === "v1"')
    expect(workflow).toContain('capabilities.mutationCommandLedger === true')
    expect(workflow).toContain('capabilities.explicitUserCommands === "v1"')
    expect(workflow).toContain('capabilities.opportunityParticipationState === "v1"')
    expect(workflow).toContain('capabilities.gmailCompleteConsumption === "v1"')
    expect(workflow).toContain('capabilities.discoverySourceVerification === "v1"')
    expect(workflow).toContain('capabilities.discoveryFactAssessmentSeparation === true')
    expect(workflow).toContain('authenticatedMcp.toolSurfaceVersion === "v7"')
    for (const tool of ['get_today_brief', 'get_opportunity_detail', 'get_coverage_status', 'get_workspace_integrity', 'list_reminder_intents', 'get_external_capabilities', 'add_opportunities', 'ingest_discovery_run', 'ingest_gmail_run']) {
      expect(workflow).toContain(`"${tool}"`)
    }
    expect(workflow).toContain('expectedAuthority === "transactional" ? [')
    expect(workflow).toContain('"apply_user_command"')
    expect(workflow).toContain('"semantic_intake"')
    expect(workflow).toContain('"resolve_semantic_decision"')
    expect(workflow).toContain('"undo_semantic_command"')
    expect(workflow).toContain('"ingest_paia_input"')
    expect(workflow).toContain('capabilities.paiaOwnerIntake === "v1"')
    expect(workflow).toContain('capabilities.reminderIntent === "v1"')
    expect(workflow).toContain('capabilities.externalReminderCapabilityTruth === "v1"')
    expect(workflow).toContain('capabilities.crossSourceSemanticDedupe === "v1"')
    expect(workflow).toContain('Verify production contract before Pages publication')
    expect(workflow).not.toContain('PJSDAS_SELF_TEST_EMAIL')
    expect(workflow).not.toContain('PJSDAS_SELF_TEST_PASSWORD')
    expect(workflow).not.toContain('PJSDAS_REQUIRE_AUTHENTICATED_SELF_TEST')
    expect(workflow.indexOf('Verify production contract before Pages publication'))
      .toBeLessThan(workflow.indexOf('uses: actions/upload-pages-artifact@v3'))
  })

  it('keeps the public health contract aligned with the release gate', () => {
    expect(health).toContain("autonomousIngestion: 'v1.9'")
    expect(health).toContain('ingestionReconciliationLedger: true')
    expect(health).toContain('coverageStatusRead: true')
    expect(health).toContain('trustedMonitorIngestion: true')
    expect(health).toContain('trustedGmailIngestion: true')
    expect(health).toContain("stableAccountSession: 'v1.8.1'")
    expect(health).toContain('releaseIdentityBinding: true')
    expect(health).toContain('authenticatedMcpToolSurface: true')
    expect(health).toContain("todayBriefReadModel: 'v1'")
    expect(health).toContain("todayAgendaReadModel: 'v1'")
    expect(health).toContain("opportunityDecisionReadModel: 'v1'")
    expect(health).toContain("opportunityConclusionDetail: 'v1'")
    expect(health).toContain("latestStartPlanning: 'v1'")
    expect(health).toContain("paiaOwnerIntake: 'v1'")
    expect(health).toContain("reminderIntent: 'v1'")
    expect(health).toContain("externalReminderCapabilityTruth: 'v1'")
    expect(health).toContain("crossSourceSemanticDedupe: 'v1'")
    expect(health).toContain('toolSurfaceVersion: AUTHENTICATED_MCP_TOOL_SURFACE_VERSION')
    expect(health).toContain('releaseRequiredTools: authenticatedMcpReleaseRequiredTools(workspace.authority)')
    expect(health).toContain('commitSha: backendReleaseCommit(releaseEnvironment) ?? null')
  })
})
