import { expect, test } from '@playwright/test'

test('deadline-only settings retain facts and recovery in both interface languages', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: '今天', exact: true })).toBeVisible()
  await page.locator('.tsui-topbar').getByRole('button', { name: /设置/ }).click()
  await expect(page.locator('.settings-group > summary').filter({ hasText: '决策规则' })).toHaveCount(0)
  await expect(page.locator('.settings-group > summary').filter({ hasText: '数据与恢复' })).toBeVisible()
  const interfaceGroup = page.locator('details.settings-group').filter({ has: page.locator('summary strong').filter({ hasText: /^(界面|Interface)$/ }) })
  await interfaceGroup.locator('summary').click()
  await interfaceGroup.getByRole('button', { name: 'EN', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Settings', exact: true })).toBeVisible()
  await expect(page.locator('.settings-group > summary').filter({ hasText: /Decision Rules|Decision policy/ })).toHaveCount(0)
  await expect(page.locator('.settings-group > summary').filter({ hasText: 'Discovery preferences' })).toBeVisible()
  await expect(page.locator('.settings-group > summary').filter({ hasText: 'Data & recovery' })).toBeVisible()
  await expect(page.locator('.settings-group > summary').filter({ hasText: 'History & audit' })).toBeVisible()
  await page.getByRole('button', { name: /Jobs/, exact: true }).click()
  await page.goBack()
  await expect(page.getByRole('heading', { name: 'Settings', exact: true })).toBeVisible()
  await expect(page.locator('.rules-page')).toHaveCount(0)
})
