-- PJSDAS AI-operated production foundation.
--
-- This migration establishes the server-side transactional workspace, command
-- ledger, and explicit delegated-client authorization grants required by the
-- Round 0 frozen contract. It does not migrate or overwrite any existing
-- Google Drive workspace. Activation is a separate, explicit migration step.

create table if not exists public.pjsdas_workspaces (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references auth.users(id) on delete cascade,
  snapshot jsonb not null,
  revision bigint not null default 0 check (revision >= 0),
  schema_version integer not null default 1 check (schema_version > 0),
  migrated_from text,
  source_fingerprint text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pjsdas_command_ledger (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.pjsdas_workspaces(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  command_id text not null,
  operation text not null,
  payload_hash text not null,
  expected_revision bigint,
  principal_kind text not null,
  client_id text,
  provenance jsonb not null default '{}'::jsonb,
  effective_time timestamptz,
  status text not null check (status in ('COMMITTED', 'FAILED')),
  resulting_revision bigint,
  receipt jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, command_id)
);

create index if not exists pjsdas_command_ledger_workspace_created_idx
  on public.pjsdas_command_ledger (workspace_id, created_at desc);

create table if not exists public.pjsdas_authorization_grants (
  user_id uuid not null references auth.users(id) on delete cascade,
  client_id text not null,
  source_id text not null,
  capability text not null check (capability in ('ingest_discovery_run', 'ingest_gmail_run')),
  granted_at timestamptz not null default now(),
  revoked_at timestamptz,
  primary key (user_id, client_id, source_id, capability)
);

create index if not exists pjsdas_authorization_grants_active_idx
  on public.pjsdas_authorization_grants (user_id, client_id, capability, source_id)
  where revoked_at is null;

alter table public.pjsdas_workspaces enable row level security;
alter table public.pjsdas_command_ledger enable row level security;
alter table public.pjsdas_authorization_grants enable row level security;

revoke all on table public.pjsdas_workspaces from anon, authenticated;
revoke all on table public.pjsdas_command_ledger from anon, authenticated;
revoke insert, update, delete on table public.pjsdas_authorization_grants from anon, authenticated;
grant select on table public.pjsdas_authorization_grants to authenticated;

drop policy if exists pjsdas_authorization_grants_select_own on public.pjsdas_authorization_grants;
create policy pjsdas_authorization_grants_select_own
  on public.pjsdas_authorization_grants
  for select
  to authenticated
  using (auth.uid() = user_id);

create or replace function public.pjsdas_bootstrap_workspace(
  target_user_id uuid,
  initial_snapshot jsonb,
  initial_schema_version integer,
  initial_source_fingerprint text default null,
  initial_migrated_from text default null
)
returns table (
  outcome text,
  workspace_id uuid,
  revision bigint,
  snapshot jsonb
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  existing public.pjsdas_workspaces%rowtype;
begin
  if target_user_id is null or initial_snapshot is null then
    raise exception 'PJSDAS bootstrap requires user and snapshot.' using errcode = '22023';
  end if;

  insert into public.pjsdas_workspaces (
    user_id, snapshot, revision, schema_version, migrated_from, source_fingerprint
  )
  values (
    target_user_id,
    initial_snapshot,
    0,
    initial_schema_version,
    initial_migrated_from,
    initial_source_fingerprint
  )
  on conflict (user_id) do nothing;

  select * into existing
  from public.pjsdas_workspaces
  where user_id = target_user_id;

  if not found then
    raise exception 'PJSDAS workspace bootstrap failed.' using errcode = 'P0001';
  end if;

  outcome := case when existing.revision = 0 and existing.snapshot = initial_snapshot then 'CREATED_OR_MATCHED' else 'EXISTS' end;
  workspace_id := existing.id;
  revision := existing.revision;
  snapshot := existing.snapshot;
  return next;
end
$$;

create or replace function public.pjsdas_commit_workspace(
  target_user_id uuid,
  target_command_id text,
  target_operation text,
  target_payload_hash text,
  target_expected_revision bigint,
  target_snapshot jsonb,
  target_schema_version integer,
  target_principal_kind text,
  target_client_id text default null,
  target_provenance jsonb default '{}'::jsonb,
  target_effective_time timestamptz default null
)
returns table (
  outcome text,
  workspace_id uuid,
  revision bigint,
  snapshot jsonb,
  receipt jsonb
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  current_workspace public.pjsdas_workspaces%rowtype;
  existing_command public.pjsdas_command_ledger%rowtype;
  next_revision bigint;
  next_receipt jsonb;
begin
  if target_user_id is null
    or nullif(trim(target_command_id), '') is null
    or nullif(trim(target_operation), '') is null
    or nullif(trim(target_payload_hash), '') is null
    or target_snapshot is null
    or nullif(trim(target_principal_kind), '') is null then
    raise exception 'PJSDAS commit arguments are incomplete.' using errcode = '22023';
  end if;

  select * into existing_command
  from public.pjsdas_command_ledger
  where user_id = target_user_id
    and command_id = target_command_id;

  if found then
    if existing_command.payload_hash <> target_payload_hash then
      raise exception 'PJSDAS command id was reused with a different payload.' using errcode = '23505';
    end if;

    select * into current_workspace
    from public.pjsdas_workspaces
    where id = existing_command.workspace_id;

    outcome := 'ALREADY_APPLIED';
    workspace_id := existing_command.workspace_id;
    revision := existing_command.resulting_revision;
    snapshot := current_workspace.snapshot;
    receipt := existing_command.receipt;
    return next;
    return;
  end if;

  select * into current_workspace
  from public.pjsdas_workspaces
  where user_id = target_user_id
  for update;

  if not found then
    raise exception 'PJSDAS connected workspace does not exist.' using errcode = 'P0001';
  end if;

  if target_expected_revision is null or current_workspace.revision <> target_expected_revision then
    outcome := 'CONFLICT';
    workspace_id := current_workspace.id;
    revision := current_workspace.revision;
    snapshot := current_workspace.snapshot;
    receipt := jsonb_build_object(
      'commandId', target_command_id,
      'status', 'CONFLICT',
      'expectedRevision', target_expected_revision,
      'actualRevision', current_workspace.revision
    );
    return next;
    return;
  end if;

  next_revision := current_workspace.revision + 1;
  next_receipt := jsonb_build_object(
    'commandId', target_command_id,
    'status', 'COMMITTED',
    'operation', target_operation,
    'revision', next_revision
  );

  update public.pjsdas_workspaces
  set
    snapshot = target_snapshot,
    revision = next_revision,
    schema_version = target_schema_version,
    updated_at = now()
  where id = current_workspace.id;

  insert into public.pjsdas_command_ledger (
    workspace_id,
    user_id,
    command_id,
    operation,
    payload_hash,
    expected_revision,
    principal_kind,
    client_id,
    provenance,
    effective_time,
    status,
    resulting_revision,
    receipt,
    updated_at
  )
  values (
    current_workspace.id,
    target_user_id,
    target_command_id,
    target_operation,
    target_payload_hash,
    target_expected_revision,
    target_principal_kind,
    target_client_id,
    coalesce(target_provenance, '{}'::jsonb),
    target_effective_time,
    'COMMITTED',
    next_revision,
    next_receipt,
    now()
  );

  outcome := 'COMMITTED';
  workspace_id := current_workspace.id;
  revision := next_revision;
  snapshot := target_snapshot;
  receipt := next_receipt;
  return next;
end
$$;

revoke all on function public.pjsdas_bootstrap_workspace(uuid, jsonb, integer, text, text) from public, anon, authenticated;
revoke all on function public.pjsdas_commit_workspace(uuid, text, text, text, bigint, jsonb, integer, text, text, jsonb, timestamptz) from public, anon, authenticated;
grant execute on function public.pjsdas_bootstrap_workspace(uuid, jsonb, integer, text, text) to service_role;
grant execute on function public.pjsdas_commit_workspace(uuid, text, text, text, bigint, jsonb, integer, text, text, jsonb, timestamptz) to service_role;
